### ISSUE TITLE
Just a word of caution for Lite Account users outside US ...

### ISSUE THREAD

**Issue by PhilippeComte** [IBM/watson-google-assistant#20]
Users with a Lite account outside US may face the following issues while deploying the app with the devops Button to IBM Cloud : 
- With Lite accounts, the Cloud Foundry Org does not allow to create Spaces in other regions than your default region
- You cannot create more than one Lite 'Watson Assistant service' for an account (so it fails if you have one already)
- The deploy tries to create a Lite Watson instance service in US-East (which may not be offered as an option)
- The code still refers to service userid and password and not apikey and talk of workspaces not assistant/skills ( You can use the Assistant Workspace Management Node to list all your workspaces and workspace IDs ) 
- So you may have to adapt the credentials in the projet and do a deploy of your own

- Anyway thanks for the code !

**Comment by walkcoolboy** [comment]
Hi Philippe,

I am having the problem to create 'Watson Assistant service' - 'wga-assistant' when I have one already. However, I have already upgraded our account to standard instead of Lite. 

Do you know which part of the code is creating this service? I really like to debug it.

Thank you so much in advance.

Cheers,
Li
![Capture](https://user-images.githubusercontent.com/19543105/58448284-78c9aa00-815b-11e9-8bcf-c43965957a39.PNG)

**Comment by markstur** [comment]
Using the "Deploy to IBM Cloud" button, the file `manifest.yml` specifies that a wga-assistant service will be created.

Since the pattern assumes you are pushing to IBM Cloud (to get a public endpoint) there isn't run-locally documentation.  If you are familiar (or willing) with cloud foundry, you can clone the repo and tweak manifest.yml and use cf push.

**Comment by walkcoolboy** [comment]
Right. I just did a lot of search on google and getting a little more idea about this yaml setting. It seems it will create the service if it not exist, or it will use the service if it exists. I think I changed the plan tag from 'free' to 'standard' and then it is working now. Thanks again!
